-- =============================================================================
-- SAMPLE — DO NOT PUBLISH
-- Development content for the Awareness Hub. Generated by
-- supabase/scripts/make_sample_content.py (edit that file, not this one).
--
-- * Every item has is_sample = true and status 'in_review', so it can NEVER be
--   published. It is only shown while app_settings.show_sample_content = true.
-- * All text must be replaced by content written by qualified local experts
--   and reviewed before launch. Urdu text is a DRAFT.
-- =============================================================================

-- smp001: What is consent?
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp001', 'article', 'consent', 'in_review', true, true, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'parents', 'teachers', 'friends', 'community']) a where code = 'smp001';
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp001'), 'en', 'SAMPLE: What is consent?', 'Consent means a clear, free “yes”. It can be changed at any time.', 'Consent means agreeing to something freely, without pressure, fear or threats.

- Consent must be given freely. Silence or fear is not a “yes”.
- Consent can be taken back at any time.
- Agreeing to one thing does not mean agreeing to everything.
- A person who is asleep, drunk or very young cannot give consent.

If someone did something to you without your consent, it is not your fault. The responsibility belongs to the person who did it.');
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp001'), 'ur', 'نمونہ: رضامندی کیا ہے؟', 'رضامندی کا مطلب ہے واضح اور آزادانہ "ہاں"۔ اسے کسی بھی وقت بدلا جا سکتا ہے۔', 'رضامندی کا مطلب ہے کسی بات پر بغیر دباؤ، خوف یا دھمکی کے آزادانہ طور پر راضی ہونا۔

- رضامندی آزادانہ ہونی چاہیے۔ خاموشی یا خوف "ہاں" نہیں ہے۔
- رضامندی کسی بھی وقت واپس لی جا سکتی ہے۔
- ایک بات پر راضی ہونے کا مطلب ہر بات پر راضی ہونا نہیں۔
- سویا ہوا، نشے میں یا بہت کم عمر شخص رضامندی نہیں دے سکتا۔

اگر کسی نے آپ کی رضامندی کے بغیر آپ کے ساتھ کچھ کیا تو اس میں آپ کا کوئی قصور نہیں۔ ذمہ داری اس شخص کی ہے جس نے ایسا کیا۔');

-- smp002: What is harassment?
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp002', 'article', 'harassment', 'in_review', true, true, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'community', 'teachers']) a where code = 'smp002';
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp002'), 'en', 'SAMPLE: What is harassment?', 'Unwanted words or actions that make you feel unsafe, scared or humiliated.', 'Harassment is unwanted behaviour that makes a person feel unsafe, scared or humiliated. It can happen on the street, at school, at work, at home or online.

- Comments about someone’s body or looks
- Following someone, or staring to scare them
- Touching without permission
- Messages, calls or photos that are not wanted

Harassment is never the fault of the person it happens to. It does not depend on what they wear or where they go.');
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp002'), 'ur', 'نمونہ: ہراسانی کیا ہے؟', 'ناپسندیدہ باتیں یا حرکتیں جو آپ کو غیر محفوظ، خوف زدہ یا شرمندہ محسوس کرائیں۔', 'ہراسانی ایسا ناپسندیدہ رویہ ہے جو کسی کو غیر محفوظ، خوف زدہ یا شرمندہ محسوس کرائے۔ یہ گلی میں، اسکول میں، کام پر، گھر میں یا آن لائن ہو سکتی ہے۔

- کسی کے جسم یا شکل کے بارے میں تبصرے
- کسی کا پیچھا کرنا، یا ڈرانے کے لیے گھورنا
- اجازت کے بغیر چھونا
- ناپسندیدہ پیغامات، کالیں یا تصاویر

ہراسانی کبھی بھی اس شخص کا قصور نہیں جس کے ساتھ یہ ہو۔ اس کا تعلق اس بات سے نہیں کہ وہ کیا پہنتے ہیں یا کہاں جاتے ہیں۔');

-- smp003: Is this harassment? On the way to school
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp003', 'scenario', 'harassment', 'in_review', true, true, 20);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'friends', 'teachers', 'parents']) a where code = 'smp003';
insert into public.content_translations (content_id, lang, title, summary, scenario_situation, scenario_answer, scenario_actions) values ((select id from public.content_items where code = 'smp003'), 'en', 'SAMPLE: Is this harassment? On the way to school', 'A short situation, and what you can do.', 'Every day, a group of boys waits near the bridge and makes comments about a girl as she walks to school. Yesterday they followed her part of the way.', 'Yes. Repeated unwanted comments and following someone are harassment. It is not her fault, and it is not about what she wears or how she walks.', '- If you can, walk with a friend or family member.
- Tell an adult you trust, or a teacher.
- Write down the dates, times and places. This can help later.
- You can find verified support in “I Need Help”.');
insert into public.content_translations (content_id, lang, title, summary, scenario_situation, scenario_answer, scenario_actions) values ((select id from public.content_items where code = 'smp003'), 'ur', 'نمونہ: کیا یہ ہراسانی ہے؟ اسکول جاتے ہوئے', 'ایک مختصر صورتحال، اور آپ کیا کر سکتے ہیں۔', 'روزانہ لڑکوں کا ایک گروہ پل کے قریب انتظار کرتا ہے اور اسکول جاتی ایک لڑکی پر تبصرے کرتا ہے۔ کل انہوں نے کچھ دور تک اس کا پیچھا بھی کیا۔', 'جی ہاں۔ بار بار ناپسندیدہ تبصرے اور پیچھا کرنا ہراسانی ہے۔ اس میں لڑکی کا کوئی قصور نہیں، اور اس کا تعلق اس کے لباس یا چال سے نہیں۔', '- اگر ممکن ہو تو کسی دوست یا گھر کے فرد کے ساتھ جائیں۔
- کسی قابلِ بھروسہ بڑے یا استاد کو بتائیں۔
- تاریخیں، وقت اور جگہیں لکھ لیں۔ یہ بعد میں مدد دے سکتا ہے۔
- "مجھے مدد چاہیے" میں آپ تصدیق شدہ مدد تلاش کر سکتے ہیں۔');

-- smp004: Is this harassment? Pressure to send photos
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp004', 'scenario', 'online', 'in_review', true, true, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'friends', 'parents']) a where code = 'smp004';
insert into public.content_translations (content_id, lang, title, summary, scenario_situation, scenario_answer, scenario_actions) values ((select id from public.content_items where code = 'smp004'), 'en', 'SAMPLE: Is this harassment? Pressure to send photos', 'When someone online asks for private photos and makes threats.', 'Someone you met online keeps asking for private photos. When you say no, they say they will share an old picture of you with your family.', 'Yes. This is blackmail and online abuse. It is a crime in many places, and it is not your fault, even if you shared something before.', '- Do not send more photos or money.
- Keep screenshots of the messages and the account name.
- Block and report the account on the app.
- Tell someone you trust. You can find verified support in “I Need Help”.');
insert into public.content_translations (content_id, lang, title, summary, scenario_situation, scenario_answer, scenario_actions) values ((select id from public.content_items where code = 'smp004'), 'ur', 'نمونہ: کیا یہ ہراسانی ہے؟ تصاویر بھیجنے کا دباؤ', 'جب کوئی آن لائن نجی تصاویر مانگے اور دھمکیاں دے۔', 'کوئی شخص جس سے آپ آن لائن ملے، بار بار نجی تصاویر مانگتا ہے۔ جب آپ انکار کرتے ہیں تو وہ کہتا ہے کہ وہ آپ کی ایک پرانی تصویر آپ کے گھر والوں کو بھیج دے گا۔', 'جی ہاں۔ یہ بلیک میلنگ اور آن لائن زیادتی ہے۔ بہت سی جگہوں پر یہ جرم ہے، اور اس میں آپ کا کوئی قصور نہیں، چاہے آپ نے پہلے کچھ شیئر کیا ہو۔', '- مزید تصاویر یا رقم نہ بھیجیں۔
- پیغامات اور اکاؤنٹ کے نام کے اسکرین شاٹ محفوظ رکھیں۔
- ایپ پر اکاؤنٹ کو بلاک اور رپورٹ کریں۔
- کسی قابلِ بھروسہ شخص کو بتائیں۔ "مجھے مدد چاہیے" میں تصدیق شدہ مدد موجود ہے۔');

-- smp005: Is it abuse if there is no hitting?
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp005', 'faq', 'domestic', 'in_review', true, true, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'community', 'friends']) a where code = 'smp005';
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp005'), 'en', 'SAMPLE: Is it abuse if there is no hitting?', 'Abuse is not only physical.', 'Yes, it can be. Abuse is not only hitting. It can also be:

- Controlling who you see, where you go or what you wear
- Taking your money or documents
- Threats, constant insults or making you afraid
- Forcing any sexual act, including within marriage

You deserve to feel safe at home. Support is available, and you can decide what to do next.');
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp005'), 'ur', 'نمونہ: اگر مار پیٹ نہ ہو تو کیا پھر بھی یہ زیادتی ہے؟', 'زیادتی صرف جسمانی نہیں ہوتی۔', 'جی ہاں، ہو سکتی ہے۔ زیادتی صرف مار پیٹ نہیں۔ یہ یہ بھی ہو سکتی ہے:

- یہ کنٹرول کرنا کہ آپ کس سے ملیں، کہاں جائیں یا کیا پہنیں
- آپ کی رقم یا دستاویزات لے لینا
- دھمکیاں، مسلسل توہین یا آپ کو خوف زدہ رکھنا
- کسی بھی جنسی عمل پر مجبور کرنا، شادی کے اندر بھی

گھر میں محفوظ محسوس کرنا آپ کا حق ہے۔ مدد موجود ہے، اور آگے کیا کرنا ہے یہ آپ طے کر سکتے ہیں۔');

-- smp006: What counts as stalking?
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp006', 'faq', 'stalking', 'in_review', true, false, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'friends']) a where code = 'smp006';
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp006'), 'en', 'SAMPLE: What counts as stalking?', 'Repeated behaviour that makes you feel watched or afraid.', 'Stalking is when someone keeps contacting, following or watching a person in a way that makes them afraid.

- Following you or waiting outside your home, school or work
- Repeated calls or messages after you asked them to stop
- Tracking your phone or checking your accounts

Keeping a simple record of what happens (dates, times, screenshots) can help if you decide to get support.');
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp006'), 'ur', 'نمونہ: پیچھا کرنا کسے کہتے ہیں؟', 'بار بار کا ایسا رویہ جس سے لگے کہ آپ پر نظر رکھی جا رہی ہے یا آپ خوف زدہ ہوں۔', 'پیچھا کرنا یہ ہے کہ کوئی شخص بار بار کسی سے رابطہ کرے، اس کا پیچھا کرے یا اس پر نظر رکھے، جس سے وہ خوف زدہ ہو۔

- آپ کا پیچھا کرنا یا آپ کے گھر، اسکول یا دفتر کے باہر انتظار کرنا
- منع کرنے کے بعد بھی بار بار کالیں یا پیغامات
- آپ کے فون کو ٹریک کرنا یا آپ کے اکاؤنٹس دیکھنا

جو کچھ ہو اس کا سادہ ریکارڈ (تاریخیں، وقت، اسکرین شاٹ) رکھنا مدد لینے کا فیصلہ کرنے پر کام آ سکتا ہے۔');

-- smp007: Quick quiz: consent and boundaries
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp007', 'quiz', 'consent', 'in_review', true, false, 20);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'teachers', 'friends']) a where code = 'smp007';
insert into public.content_translations (content_id, lang, title, summary, quiz) values ((select id from public.content_items where code = 'smp007'), 'en', 'SAMPLE: Quick quiz: consent and boundaries', 'Three short questions. Your answers stay on your phone.', '[{"prompt": "Someone says “yes” because they are afraid. Is that consent?", "options": ["Yes", "No"], "correct": 1, "explanation": "Consent must be free. A “yes” given out of fear is not consent."}, {"prompt": "Can a person change their mind after saying yes?", "options": ["Yes, at any time", "No, a yes is final"], "correct": 0, "explanation": "Consent can be taken back at any time."}, {"prompt": "A friend tells you something bad happened to them. What helps most?", "options": ["Asking what they did wrong", "Listening and believing them", "Telling others straight away"], "correct": 1, "explanation": "Listening without blame helps. Let them decide what happens next."}]'::jsonb);
insert into public.content_translations (content_id, lang, title, summary, quiz) values ((select id from public.content_items where code = 'smp007'), 'ur', 'نمونہ: مختصر کوئز: رضامندی اور حدود', 'تین مختصر سوال۔ آپ کے جواب آپ کے فون پر ہی رہتے ہیں۔', '[{"prompt": "کوئی شخص ڈر کی وجہ سے \"ہاں\" کہتا ہے۔ کیا یہ رضامندی ہے؟", "options": ["ہاں", "نہیں"], "correct": 1, "explanation": "رضامندی آزادانہ ہونی چاہیے۔ ڈر سے کہی گئی \"ہاں\" رضامندی نہیں۔"}, {"prompt": "کیا کوئی شخص \"ہاں\" کہنے کے بعد اپنا ارادہ بدل سکتا ہے؟", "options": ["ہاں، کسی بھی وقت", "نہیں، ہاں آخری ہے"], "correct": 0, "explanation": "رضامندی کسی بھی وقت واپس لی جا سکتی ہے۔"}, {"prompt": "ایک دوست آپ کو بتاتا ہے کہ اس کے ساتھ کچھ برا ہوا۔ سب سے زیادہ کیا مدد دیتا ہے؟", "options": ["یہ پوچھنا کہ اس نے کیا غلطی کی", "سننا اور یقین کرنا", "فوراً دوسروں کو بتا دینا"], "correct": 1, "explanation": "بغیر الزام کے سننا مدد دیتا ہے۔ آگے کیا ہو، یہ انہیں طے کرنے دیں۔"}]'::jsonb);

-- smp008: Talking with children about body safety
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp008', 'article', 'child-safety', 'in_review', true, true, 10);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['parents', 'teachers', 'community']) a where code = 'smp008';
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp008'), 'en', 'SAMPLE: Talking with children about body safety', 'Simple words that help children speak up.', 'Children are safer when they know they can talk to you about anything.

- Teach the correct names for body parts.
- Explain that no one should touch their private parts, and that they can say no, even to adults they know.
- Say there are no secrets that make them feel scared or uncomfortable.
- Tell them they will never be in trouble for telling you.

If a child tells you something, stay calm, believe them and thank them for telling you.');
insert into public.content_translations (content_id, lang, title, summary, body) values ((select id from public.content_items where code = 'smp008'), 'ur', 'نمونہ: بچوں سے جسمانی تحفظ کے بارے میں بات کرنا', 'سادہ الفاظ جو بچوں کو بولنے میں مدد دیتے ہیں۔', 'بچے زیادہ محفوظ ہوتے ہیں جب انہیں معلوم ہو کہ وہ آپ سے ہر بات کر سکتے ہیں۔

- انہیں جسم کے حصوں کے درست نام سکھائیں۔
- بتائیں کہ کسی کو ان کے نجی حصوں کو چھونے کا حق نہیں، اور وہ جاننے والے بڑوں کو بھی "نہیں" کہہ سکتے ہیں۔
- بتائیں کہ ایسا کوئی راز نہیں ہونا چاہیے جو انہیں ڈرائے یا پریشان کرے۔
- انہیں یقین دلائیں کہ آپ کو بتانے پر وہ کبھی مشکل میں نہیں پڑیں گے۔

اگر کوئی بچہ آپ کو کچھ بتائے تو پرسکون رہیں، اس پر یقین کریں اور بتانے کا شکریہ ادا کریں۔');

-- smp009: Don't Let Fear Silence You
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp009', 'campaign', 'harassment', 'in_review', true, false, 90);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'parents', 'teachers', 'friends', 'community']) a where code = 'smp009';
insert into public.content_translations (content_id, lang, title, summary, body, image_url, image_alt, share_text) values ((select id from public.content_items where code = 'smp009'), 'en', 'SAMPLE: Don''t Let Fear Silence You', 'Learn. Prevent. Protect. Report. Support.', 'Nobody should have to stay silent because of fear. Share this message to let people know that support exists.', '/samples/campaign-smp009-en.jpg', 'Poster with the words: Don''t Let Fear Silence You. Learn. Prevent. Protect. Report. Support.', 'Don''t Let Fear Silence You. Learn. Prevent. Protect. Report. Support.');
insert into public.content_translations (content_id, lang, title, summary, body, image_url, image_alt, share_text) values ((select id from public.content_items where code = 'smp009'), 'ur', 'نمونہ: خوف کو اپنی آواز دبانے نہ دیں', 'سیکھیں۔ روک تھام کریں۔ تحفظ کریں۔ رپورٹ کریں۔ سہارا دیں۔', 'کسی کو بھی خوف کی وجہ سے خاموش نہیں رہنا چاہیے۔ یہ پیغام شیئر کریں تاکہ لوگ جانیں کہ مدد موجود ہے۔', '/samples/campaign-smp009-ur.jpg', 'پوسٹر جس پر لکھا ہے: خوف کو اپنی آواز دبانے نہ دیں۔', 'خوف کو اپنی آواز دبانے نہ دیں۔ سیکھیں۔ روک تھام کریں۔ تحفظ کریں۔ رپورٹ کریں۔ سہارا دیں۔');

-- smp010: No Means No
insert into public.content_items (code, type, topic_id, status, is_sample, is_core, sort_order) values ('smp010', 'campaign', 'consent', 'in_review', true, false, 91);
insert into public.content_audiences (content_id, audience_id) select id, a from public.content_items, unnest(array['women', 'men', 'friends', 'community']) a where code = 'smp010';
insert into public.content_translations (content_id, lang, title, summary, body, image_url, image_alt, share_text) values ((select id from public.content_items where code = 'smp010'), 'en', 'SAMPLE: No Means No', 'Respect boundaries. Every time.', 'A “no” is a complete answer. It does not need a reason, and it deserves respect.', '/samples/campaign-smp010-en.jpg', 'Poster with the words: No Means No. Respect boundaries. Every time.', 'No Means No. Respect boundaries. Every time.');
insert into public.content_translations (content_id, lang, title, summary, body, image_url, image_alt, share_text) values ((select id from public.content_items where code = 'smp010'), 'ur', 'نمونہ: نہیں کا مطلب نہیں', 'حدود کا احترام کریں۔ ہر بار۔', '"نہیں" ایک مکمل جواب ہے۔ اسے کسی وجہ کی ضرورت نہیں، اور یہ احترام کا حق دار ہے۔', '/samples/campaign-smp010-ur.jpg', 'پوسٹر جس پر لکھا ہے: نہیں کا مطلب نہیں۔', 'نہیں کا مطلب نہیں۔ حدود کا احترام کریں۔ ہر بار۔');
